/**
 * 
 */
package com.iris.sdmx.util;

/**
 * @author sajadhav
 *
 */
public enum SDMXWebServiceConstant {

	SUBMIT_FUSION_DATA("SUBMIT_FUSION_DATA"),
	DELETE_CODE_LIST_FUSION_DATA("DELETE_CODE_LIST_FUSION_DATA"),
	DELETE_ELE_DIMN_FUSION_DATA("DELETE_ELE_DIMN_FUSION_DATA"),
	GENERATE_DSD_FUSION("GENERATE_DSD_FUSION"),
	ECU_LOGIN("ECU_LOGIN"),
	DOWNLOAD_SDMX_DOCUMENT("DOWNLOAD_SDMX_DOCUMENT"),
	CONVERT_CSV_TO_SDMX("CONVERT_CSV_TO_SDMX"),
	CONVERT_JSON_TO_SDMX("CONVERT_JSON_TO_SDMX"),
	GET_FUSION_CONSTRAINTS("GET_FUSION_CONSTRAINTS"),
	FUSION_VALIDATION("FUSION_VALIDATION"),
	UPLOAD_FILE("uploadFile"),
	AGENCY_WISE_GENERATE_DSD_FUSION("AGENCY_WISE_GENERATE_DSD_FUSION"),
	FILE("file"),
	OWNER_GROUP_CODE_KEY("owner_group_code"),
	CODE_KEY("code"),
	PROJECT_CODE_KEY("project_code"),
	VERSION_KEY("version"),
	RETURN_ONLY_PERSISTENT_KEY("return_only_persistent"),
	CALLBACK_URL_KEY("callback_url"),
	SUBMIT_FILE_FOR_VTL_VALIDATION("SUBMIT_FILE_FOR_VTL_VALIDATION"),
	AUTHORIZATION("Authorization"),
	UUID("uuid"),
	REQUEST_ID("request_id"),
	VTL_AUTHORIZATION_KEY("vtlAuthorizationKey"),
	DOWNLOAD_RESULT_FROM_VTL("DOWNLOAD_RESULT_FROM_VTL"),
	VTL_STATUS_OF_EXECUTION("VTL_STATUS_OF_EXECUTION"),
	CALLBACK_OF_SUBMIT_FILE_FOR_VTL_VALIDATION_API("CALLBACK_OF_SUBMIT_FILE_FOR_VTL_VALIDATION_API"),
	OWNER_GROUP_CODE("VTL_OWNER_GROUP_CODE"),
	CODE("VTL_CODE"),
	PROJECT_CODE("VTL_PROJECT_CODE"),
	VERSION("VTL_VERSION"),
	RETURN_ONLY_PERSISTENT("VTL_RETURN_ONLY_PERSISTENT");

	private String name;

	private SDMXWebServiceConstant(String name) {
		this.name = name;
	}

	public String getConstantVal() {
		return name;
	}
}
